# BASE IMAGE FOR BUILD STAGE

FROM eclipse-temurin:17-jdk-jammy AS builder

# WORKDIR 

WORKDIR /app

# COPY CODE

COPY src/Main.java quotes.txt ./

# COMPILE CODE

RUN ["javac","Main.java"]

# DISTROLESS BASE IMAGE FOR RUNTIME STAGE

FROM gcr.io/distroless/java17-debian12

# WORKDIR

WORKDIR /app

# COPY

COPY --from=builder /app/Main.class /app/quotes.txt ./

# EXPOSE PORT 

EXPOSE 8000

# RUN & SERVE APPLICATION

ENTRYPOINT ["java"]

CMD ["-cp","/app","Main"]
